package com.popalay.cardme.screens

const val SCREEN_HOME = "SCREEN_HOME"
const val SCREEN_HOLDER_DETAILS = "SCREEN_HOLDER_DETAILS"
const val SCREEN_SETTINGS = "SCREEN_SETTINGS"
const val SCREEN_ADD_CARD = "SCREEN_ADD_CARD"
const val SCREEN_CARDS = "SCREEN_CARDS"
const val SCREEN_DEBTS = "SCREEN_DEBTS"
const val SCREEN_HOLDERS = "SCREEN_HOLDERS"
const val SCREEN_SCAN_CARD = "SCREEN_SCAN_CARD"
const val SCREEN_ADD_DEBT = "SCREEN_ADD_DEBT"
const val SCREEN_TRASH = "SCREEN_TRASH"
const val SCREEN_CARD_DETAILS = "SCREEN_CARD_DETAILS"